import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google"; // Adjust import if needed
import "./globals.css";
import { Analytics } from "@vercel/analytics/react";
//import { MegaMenu } from "@/components/ui/Megamenu/MegaMenu"; // Adjust path as needed
import FaqButton from "../components/FaqButton"; // Adjust path as needed

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CognitionIES pvt ltd",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <FaqButton />
        <main>{children}</main>
        <Analytics />
      </body>
    </html>
  );
}