import processImage from "@/constants/images/horizontal/01.jpg"
import mechImage from "@/constants/images/horizontal/02.jpg"
import pipingImage from "@/constants/images/horizontal/03.jpg"
import pipeStressImage from "@/constants/images/horizontal/04.jpg"
import civilImage from "@/constants/images/horizontal/05.jpg"
import StructuralImage from "@/constants/images/horizontal/06.png"
import elecImage from "@/constants/images/horizontal/07.jpg"
import InstrumentationImage from "@/constants/images/horizontal/08.jpg"
import ModularImage from "@/constants/images/horizontal/09.jpg"
import ReverseImage from "@/constants/images/horizontal/10.jpg" 
import ProcurementImage from "@/constants/images/horizontal/11.jpg" 

// This file holds all constants for the plant engineering page
import {
    Wrench,
    FlaskRound as Flask,
    Baseline as Pipeline,
    Building2,
    Fan,
    Gauge,
    ShieldCheck,
    
    Cpu,
    ClipboardList,
  } from "lucide-react";
  import { IconType } from "react-icons"; // For icon typing
  
  // Define what a service looks like
  interface Service {
    bulletPoints: string[];
    icon: IconType;
    title: string;
    description: string;
    image: string;
    alt: string;
    href: string;
  }
  
  export const PLANT_ENGINEERING_CONSTANTS = {
    // Hero Section
    HERO: {
      IMAGE: "https://images.unsplash.com/photo-1581094794329-c8112c4e5190?ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80",
      TITLE: "Plant Engineering services",
      SUBTITLE: "Innovative engineering solutions for complex challenges",
    },
  
    // About Section
    ABOUT: {
      TITLE: "Plant Engineering Solutions",
      DESCRIPTION_1: "At Cognition IES, we help industries build smarter, safer, and more efficient plants. From designing machinery and piping systems to optimizing energy use and safety compliance, we cover everything needed to keep your plant running smoothly. Whether you're setting up a new facility or upgrading an existing one, our team ensures seamless operations with practical, cost-effective solutions.",
      DESCRIPTION_2: "Description 2", // Placeholder from your code
      IMAGE: "https://images.unsplash.com/photo-1581092921461-eab62e97a780?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80",
    },
  
    // Services Section
    SERVICES: {
      TITLE: "Our Plant Engineering Services",
      SUBTITLE: "Comprehensive engineering solutions tailored to your specific needs",
      ITEMS: [
        {
          icon: ShieldCheck,
          title: "Process & Safety Engineering",
          description: "Enhancing plant processes and ensuring compliance with safety standards to minimize risks and improve efficiency.",
          image: processImage,
          alt: "Process safety equipment",
          href: "/services/plant-engineering/process-and-safety",
          bulletPoints: [
            "Preliminary P&ID",
            "Pre-Bid Engineering / FEED",
            "Hydraulic Analysis",
            "Mass & Energy Balance",
            "Utility Consumption Summary",
            "Pipeline Sizing & Line List Development",
            "HAZOP",
            "Safety & Risk Assessment (Safety Studies)",
            "HAZID",
            "SIL",
            "QRA",
            "Piping Service Index",
            "Bill of Quantities (BOQ)",
            "Preliminary Thermal Design for HE",
            "Pressure Safety Valve (PSV) Sizing",
            "Process Design & Optimization",
            "Revalidation & Retrofitting - Process Design",
            "HE Design & Thermal Rating",
            "Efficiency Assessment",
            "Process Optimization",
            "Utility Consumption Optimization",
            "Distribution Network Hydraulics and Surge Analysis",
            "Process Equipment Reassessment",
            "Hydraulics Pipeline Review",
            "Hydraulics Pump System Re-evaluation",
          ],
        },
        {
          icon: Wrench,
          title: "Mechanical Engineering",
          description: "Designing and maintaining robust mechanical systems for optimal plant performance and reliability.",
          image: mechImage,
          alt: "Mechanical engineering tools",
          href: "/services/plant-engineering#mechanical",
          bulletPoints: [
            "Equipment List & Mechanical Datasheets",
            "Equipment Drawings & Detailing",
            "Mechanical Schematic Diagrams",
            "Equipment Layout & Arrangement Drawings",
            "Fatigue & Failure Analysis (FEA)",
            "GA Drawings for Equipment",
            "Nozzle & Manhole Detail Drawings",
            "Equipment & Pipe Support Drawings",
            "Ladder & Platform Support Drawings",
            "Tray Support & Welded Internal Details",
            "Tube Bundle Detailing for Shell & Tube HE",
            "3D Modeling & Visualization",
            "Material Take-Off (MTO) & Bill of Materials (BOM)",
            "Pressure Vessels",
            "Static & Rotating Equipment",
            "HVAC System Design & Engineering",
            "Columns & Towers",
            "Heat Exchangers",
            "Storage Tanks",
            "Dryers & Cooling Towers",
            "Pumps & Pumping Systems",
            "Air & Gas Compressors System",
            "HVAC System Design Basis",
            "Heat Load Calculation",
            "Ducting Layout & Routing",
            "Duct Fabrication Drawings",
          ],
        },
        {
          icon: Pipeline,
          title: "Piping Engineering",
          description: "Crafting efficient piping systems for the safe transport of fluids and gases throughout the plant.",
          image: pipingImage,
          alt: "Piping engineering layout",
          href: "/services/plant-engineering/piping",
          bulletPoints: [
            "Overall & Unit Plot Plans",
            "Piping Layout & Design",
            "Equipment Layout & GA Drawings",
            "Piping Layout & GA Drawings",
            "Piping Isometric Drawings",
            "Line List / Line Schedule",
            "Piping Stress Analysis",
            "3D Modeling & Simulation",
            "As Built Documentation & Updates",
            "Piping Support Design & Load Calculations",
            "Nozzle Orientation, Spool, Special Supports & Platform Design Drawings",
            "Piping MTO & BOM",
            "Material & Specification Management",
            "Insulation, Painting, & Material Spec.",
            "Specialty Items List",
            "Valve & Piping Special Component Data Sheets",
            "Analysis & Modeling",
          ],
        },
        {
          icon: Gauge,
          title: "Piping Stress Analysis",
          description: "Analyzing piping systems to ensure structural integrity under various operating conditions.",
          image: pipeStressImage,
          alt: "Piping stress analysis dashboard",
          href: "/services/plant-engineering/piping-stress-analysis",
          bulletPoints: [
            "Finite Element Analysis (FEA)",
            "Types of Piping Stress Analysis",
            "Surge & Slug Flow Analysis",
            "Fatigue & Creep Assessment",
            "Displacement & Deflection Studies",
            "Occasional Load Analysis (Wind & Seismic)",
            "Piping Flexibility & Support Optimization",
            "Engineering Calculations & Validations",
            "Elastic & Plastic Stress Analysis",
            "Trunnion Support Load Check",
            "Flange Integrity Analysis (NC-3685.3 & API Standards)",
            "Upheaval & Buckling Analysis",
            "Weld Strength Evaluation",
            "U Bolt Load Calculations",
            "Collapse & Structural Stability",
            "Sustained / Longitudinal Stress Evaluation",
          ],
        },
        {
          icon: Building2,
          title: "Civil Engineering",
          description: "Providing foundational civil engineering solutions for durable and safe plant infrastructure.",
          image: civilImage,
          alt: "Civil engineering construction",
          href: "/services/plant-engineering/civil",
          bulletPoints: [
            "Site Preparation, Grading, and Fencing",
            "Site Development & Infrastructure",
            "Underground Utilities, Valve Pits, Duct Banks, and Culverts",
            "Admin Buildings, Canteens, Utility Blocks, and Non-Plant Structures",
            "Drainage, Roads, and Paving Layouts",
            "Foundation Engineering",
            "Industrial & Commercial Building Design",
            "Equipment Foundations Static & Dynamic Analysis",
            "Foundation Layouts & Design Reports",
          ],
        },
        {
          icon: Building2,
          title: "Structural Engineering",
          description: "Designing strong, stable structures to support plant operations and withstand environmental challenges.",
          image:StructuralImage ,
          alt: "Structural engineering framework",
          href: "/services/plant-engineering/structural",
          bulletPoints: [
            "Hot Oil Heater Supporting Structures",
            "Specialized Structural Engineering",
            "Structural Detailing",
            "Waste Heat Recovery Units (WHRU)",
            "Reactor Structures & FPSO Modules",
            "Technological Structures & Heavy Industrial Frameworks",
            "GA, Erection, and Fabrication Drawings",
            "Structural Stress Analysis",
            "Barge Transport & Offshore Load Handling",
            "Dropped Object Impact Studies",
            "Transit & Survival Load Assessments",
            "Fire, Blast, and Fatigue Conditions",
            "In-Place Analysis (Operating, Damage, Extreme Scenarios)",
            "Pipe Supports, Pipe Racks, Shelters, Platforms, Crossovers, and Sleepers",
            "Transportation & Lifting Engineering",
            "Lifting Analysis, Reports & Drawings",
            "Structural Integrity Assessments",
          ],
        },
        {
          icon: Fan,
          title: "Electrical Engineering",
          description: "Implementing reliable electrical systems to power plant operations efficiently and safely.",
          image: elecImage,
          alt: "Electrical engineering panel",
          href: "/services/plant-engineering/electrical",
          bulletPoints: [
            "Electrical Design Basis",
            "Preliminary Load List & Equipment Sizing",
            "Preliminary Single Line Diagram (SLD)",
            "Main Equipment & Switchgear Layouts",
            "Electrical Equipment Specifications & Datasheets",
            "Final Single Line Diagram (SLD)",
            "Electrical Equipment & Components Layouts",
            "Earthing System Design & Layouts",
            "HV/LV Power Cable Sizing & Routing",
            "Cable, Illumination & Lightning Protection Layouts",
            "Detailed Load List & Feeder Lists for Switchgear, MCCs, DBs",
            "Plant Intercommunication System",
            "Power & Control Cable Listings",
            "Electrical Bill of Materials (BOM)",
            "Erection Tender Preparation",
            "As Built Drawings & Documentation",
            "Relay Setting Schedules & Protection Coordination Charts",
          ],
        },
        {
          icon: Gauge,
          title: "Instrumentation Engineering",
          description: "Integrating advanced instrumentation for precise monitoring and control of plant processes.",
          image: InstrumentationImage,
          alt: "Instrumentation control system",
          href: "/services/plant-engineering/instrumentation",
          bulletPoints: [
            "Instrumentation Design Basis",
            "Basic Engineering",
            "I/O List",
            "Instrument Cable Block Diagram",
            "Instrument Installation Details",
            "Safety & Risk Assessment (Safety Studies)",
            "Preliminary Instrument List / Index",
            "Instrument Process Datasheets",
            "Hook-Up Drawings",
            "Process Optimization",
            "Final Instrumentation Design Basis",
            "Instrument Location Layout",
            "Instrument Index & Specification Datasheets",
            "DCS Control Room Layout",
            "Cable Tray & Fittings MTO",
            "Junction Box Grouping",
            "Instrument Cable Schedule and Wiring Diagram",
            "I/O List & Cause-Effect Diagram/List",
            "Cable Tray Routing & Layout",
            "Hook-Up Drawings & Erection Hardware MTO",
            "Instrument Termination Drawings",
            "As-Built Drawings & Documentation",
          ],
        },
        {
          icon: Cpu,
          title: "Modular Package",
          description: "Delivering pre-engineered modular solutions for faster installation and operational flexibility.",
          image: ModularImage,
          alt: "Modular plant package",
          href: "/services/plant-engineering/modular-package",
          bulletPoints: [
            "3D Modeling of Skid Package Design",
            "Modular Skid Design & Engineering",
            "Fabrication Isometric Drawings",
            "Monorail Calculations",
            "MTO & BOM Preparation",
            "Structural Steel Calculations (Including Anchor/Foundation Loads)",
            "E&I Skid Engineering (Cable Tray, Junction Box, Small-Bore Containment, etc.)",
            "Custody Transfer Skids",
            "Heat Exchanger Skids",
            "High-Pressure Systems",
            "2D General Arrangement Drawings",
            "Static & Rotating Equipment",
            "Detailed Structural Fabrication Drawings",
            "Lifting Lug Design & Details",
            "Piping & Structural Stress Analysis Reports",
            "Weight & COG Calculation for Lifting Arrangement",
            "Lifting Arrangement Drawings and Calculations",
            "Fuel Oil Unloading & Transfer Skids",
            "Corrosion Inhibitor Skids",
            "Chemical Process Skids (Metering, Injection, Dosing, Feeding, Transport, Blending, Extraction & Filtration)",
          ],
        },
        {
          icon: Flask,
          title: "Reverse Engineering",
          description: "Analyzing existing systems to recreate or improve designs for enhanced performance.",
          image: ReverseImage,
          alt: "Reverse engineering process",
          href: "/services/plant-engineering/reverse-engineering",
          bulletPoints: [
            "High Precision Laser Scanning for Existing Plants & Equipment",
            "Advanced Scanning & Data Capture",
            "Creating Accurate 3D Laser Models from Scanned Point Cloud Data",
            "Supported File Formats: .pptx, .pcg, .xyz, .dwg, .dgn, .rvt, .fls",
            "Extraction & Submission of Detailed Engineering Drawings & Reports",
            "Deliverables & Final Outputs",
            "Integration of Reverse Engineered Models into Existing Design Workflows",
            "Converting As Built Data into Millimeter Accurate 3D CAD Models",
            "3D Modeling & Data Translation",
            "Generating Dumb Models from Laser Scans",
            "Transforming Dumb Models into Intelligent Models",
          ],
        },
        {
          icon: ClipboardList,
          title: "Procurement Support",
          description: "Streamlining procurement processes to source quality materials and equipment on time and within budget.",
          image:ProcurementImage,
          alt: "Procurement planning meeting",
          href: "/services/plant-engineering/procurement-support",
          bulletPoints: [
            "Preparation of Inquiry Specifications for Equipment, E&I, Piping, C&S",
            "Inquiry & Vendor Management",
            "Floating Inquiries & Managing Vendor Communication",
            "Development of Approved Vendor Lists",
            "Evaluation of Vendor Offers & Comparison Reports",
            "Vendor Evaluation & Coordination",
            "Preparation of Technical Queries (TQ) & Clarifications",
            "Vendor Coordination & Follow-Ups",
            "Review & Approval of Vendor Drawings",
            "Review & Implementation",
            "Integration & Implementation of Vendor Data into Engineering",
          ],
        },
      ] as unknown as Service[],
    },
  
    // FAQ Section
    FAQ: {
      TITLE: "Frequently Asked Questions",
      SUBTITLE: "Find answers to common questions about our engineering services",
      ITEMS: [
        {
          question: "What is plant engineering, and why is it important?",
          answer: "Plant engineering covers everything needed to design, build, and maintain industrial plants. It ensures smooth operations, safety compliance, and efficiency, helping businesses reduce downtime and operational costs.",
        },
        {
          question: "What industries do you serve?",
          answer: "We work across industries like automotive, aerospace, heavy machinery, energy, healthcare, and manufacturing. Our services allows us to create tailored solutions for various plant operations.",
        },
        {
          question: "Can you help upgrade an existing plant?",
          answer: "Yes! We specialize in modernizing plants by upgrading machinery, automation systems, energy management, and safety protocols to meet current industry standards.",
        },
        {
          question: "Do you offer digital solutions for plant management?",
          answer: "Yes! Our Digitalization & Industry 4.0 services use IoT, AI, and automation to enhance real-time monitoring, predictive maintenance, and process optimization for seamless plant operations.",
        },
        {
          question: "What is your approach to project management in plant engineering?",
          answer: "We manage projects end-to-end, covering planning, design, execution, and final testing. Our structured approach ensures timely completion while staying within budget and meeting all requirements.",
        },
        {
          question: "Can you customize your solutions for our plant’s needs?",
          answer: "Absolutely! We provide tailored plant engineering solutions to align with your specific requirements, ensuring maximum efficiency, safety, and cost-effectiveness.",
        },
      ],
    },
  
    // Animation Variants
    ANIMATIONS: {
      FADE_IN: {
        initial: { opacity: 0, y: 20 },
        animate: { opacity: 1, y: 0 },
        transition: { duration: 0.5 },
      },
    },
  };